
name: Deployment

on:
  workflow_run:
    workflows: ["CI CD Workflow"]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Download Test Artifact
        uses: actions/download-artifact@v3
        with:
          name: test_results
      
      - name: Read Test Result Data
        id: results
        run: |
          content=`cat test_results.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
          echo $content
      
      - name: Verifying Test Results
        if: ${{ fromJson(steps.results.outputs.packageJson).success == false }}
        run: set -eo pipefail

      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install Dependencies
        run: npm install